//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO_Exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkk
    {
        public int Id { get; set; }
        public System.DateTime DataSale { get; set; }
        public int IdDisc { get; set; }
        public int IdBuyer { get; set; }
        public decimal Summ { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Disc Disc { get; set; }
    }
}
